# Generated by Django 4.2.6 on 2024-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='netweight',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
